name: app_ocr_japan
description: "A Japanese learning app with OCR feature."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ไอคอนสไตล์ iOS
  cupertino_icons: ^1.0.8

  # ✅ ML Kit modules (ชุดที่เข้ากันแน่นอน)
  google_mlkit_commons: ^0.11.0
  google_mlkit_digital_ink_recognition: ^0.14.1
  # ถ้ายังต้องการ OCR จากภาพ (Text Recognition) ให้เปิดได้
  google_mlkit_text_recognition: ^0.15.0

  # สำหรับบันทึกไฟล์ / ประวัติ
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
